### PR TITLE
Fixed test urls

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
fixes https://github.com/mitodl/pylti/issues/85

Changes URL in the test from`/initial_unknown` to `/initial_student` on @brianjbeach suggestion.

@brianjbeach @pdpinch

### CODE REVIEW

**Comment by pdpinch** [comment]
@brianjbeach is this what you had in mind?

**Comment by brianjbeach** [comment]
BTW: sorry for the delay. I am not getting notifications about this project and I cannot figure out why. I get too many notifications about everything else:)

**Comment by amir-qayyum-khan** [comment]
fixed @brianjbeach

**Comment by pdpinch** [comment]
@amir-qayyum-khan rebase?

**Comment by amir-qayyum-khan** [comment]
Done @pdpinch

**Pull request merged**
