### PR TITLE
0.4.0 Release to master branch

### PR DESCRIPTION
**Pull request by carsongee**

### CODE REVIEW

**Comment by jetej** [comment]
rc/0.4.0 does not seem to make a difference for mit_lti_flask_sample.  I had tested this using an existing LTI component on the DevOps course and changing the requirements.txt to point to the rc/0.4.0 commit https://github.com/mitodl/pylti/commit/7facd92ed2c876d3b3208d42cf590ec15c903776

**Comment by carsongee** [comment]
Awesome, thanks for doing the manual testing.  I really appreciate it.  We good to go then @pdpinch or do you want to do some further verification?

**Comment by pdpinch** [comment]
Unless you want to wait to hear from some of other contributors, I'm good 

:+1:

**Comment by carsongee** [comment]
Cool, merged and released to PyPi

**Comment by jetej** [comment]
Glad to help!

**Pull request merged**
