### PR TITLE
Bypass any role check for 'any'

### PR DESCRIPTION
**Pull request by velochy**
Simple fix for #42 Draconian role checking

### CODE REVIEW

**Comment by carsongee** [comment]
Can you also add a test similar to https://github.com/mitodl/pylti/blob/master/pylti/tests/test_flask.py#L362-L369 but with the role set to some random string when calling `generate_launch_request`?

**Comment by velochy** [comment]
Done. added two tests and fixed a small bug that I discovered with one of them. Should be fine now :)

**Comment by carsongee** [comment]
Awesome, thanks so much for the contribution.

**Comment by carsongee** [comment]
This is now released PyPi, thanks again for the contribution

**Pull request merged**
